### ISSUE TITLE
[fix] Docker-compose 이름 변경

### ISSUE THREAD

**Issue by kckoh** [SVTeamJ/DeepBlue#33]
## 🤔 오류 내용
ec2에서 Docker-compose가 인식이 안되서 docker-compose로 변경 해야됩니다
<br>

## 🚩 오류 발견 위치
<br>

## ⚠ 에러 캡쳐
주요 에러 stack trace를 캡쳐해주세요!
<br>

**Comment by ppinkypeach** [comment]
수고하셨습니다
